analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_element:        error
    unused_import:         error
    unused_local_variable: error
    dead_code:             error

linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - hash_and_equals
    - prefer_is_not_empty
    - prefer_equal_for_default_values
    - prefer_constructors_over_static_methods
    - unnecessary_null_in_if_null_operators

dartfmt:
  line-length: 140
