name: boksl_subway
description: "실시간 수도권 지하철 도착시간 안내"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter
  logging: ^1.0.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/stationList.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/boksl_subway.png"